---
# file: roles/common/tasks/docker_base_image.yml

- name: ensure datawire repository information is present before image build
  template:
    dest: "{{ microwizard_docker_images }}/base/datawire-repository"
    src: datawire-repository.j2
  tags:
    - common
    - base

- name: ensure base image is built
  docker_image:
    name: microwizard/base
    nocache: no
    path: "{{ microwizard_docker_images }}/base"
    state: present
  notify:
    - list untagged images
    - show untagged images
    - remove untagged images
  tags:
    - common
    - base