---
# file: roles/lobster/tasks/main.yml

- name: generate lobsters database configuration
  template:
    src: database.yml.j2
    dest: "{{ microwizard_sources }}/lobsters/config/database.yml"
  tags:
    - lobsters

- name: generate lobsters secret
  template:
    src: production.rb.j2
    dest: "{{ microwizard_sources }}/lobsters/config/initializers/secret_token.rb"
  tags:
    - lobsters

- name: generate lobsters url info
  template:
    src: production.rb.j2
    dest: "{{ microwizard_sources }}/lobsters/config/initializers/production.rb"
  tags:
    - lobsters

- name: start the lobsters container
  docker:
    name: lobsters
    image: microwizard/generic-service
    env:
      container_name: lobsters
      exposed_port: 3000
      dockerhost: 192.168.22.10 # needs to be made dynamic
      routable_address: 192.168.22.10
      mapped_port: 3000
      RAILS_ENV: "{{ lobsters_rails_env }}"
      SECRET_KEY_BASE: "{{ lobsters_secret_key_base }}"
    expose:
      - "{{ exposed_port }}"
    ports: "{{ service_ports }}"
    volumes:
      - "{{ microwizard_sources }}/lobsters:/usr/src/service"
      - "/var/run/docker.sock:/var/run/docker.sock"
    links: "{{ service_links }}"
    state: started
  tags:
    - lobsters
