---
# file: lobster-popularity-service/tasks/add.yml

# This is an extremely poor solution to the problem of versioning new service deployments, but, lets get it done for v1
# and iterate on it after. Basically we're going to do the following things:
#
# 1. copy the main sources from their main location to a new FS location
# 2. checkout a specific committed version
# 3. mount the copied and checked out version as the containers data volume

- name: create the services volume directory
  file:
    path: /tmp/lobsters-popularity_{{ git_commit }}
    state: directory
  tags:
    - lobsters_popularity

- name: checkout source tree
  command: "git --work-tree=/tmp/lobsters-popularity_{{ git_commit }} checkout {{ git_commit }} -- ."
  args:
    chdir: "{{ microwizard_sources }}/lobsters-popularity"
  tags:
    - lobsters_popularity

- name: generate lobsters-popularity configuration
  template:
    src: config.yml.j2
    dest: "/tmp/lobsters-popularity_{{ git_commit }}/config.yml"
  tags:
    - lobsters_popularity

- name: build the lobster-popularity service image
  docker_image:
    name: microwizard/lobsters-popularity
    nocache: no
    path: "{{ microwizard_docker_images }}/lobsters-popularity"
    state: build
  tags:
    - lobsters_popularity_base

- name: generate a container name
  command: "python {{ microwizard_sources }}/microwizard/mw.py generate-name"
  register: lobsters_popularity_container_name

- name: start the lobsters-popularity containers
  docker:
    name: "{{ lobsters_popularity_container_name.stdout }}"
    image: microwizard/lobsters-popularity
    env:
      container_name: "{{ lobsters_popularity_container_name.stdout }}"
      exposed_port: 5001
    expose:
      - 5001
    ports:
      - 5001
    volumes:
      - "/tmp/lobsters-popularity_{{ git_commit }}:/usr/src/lobsters-popularity"
      - "/var/run/docker.sock:/var/run/docker.sock"
    links:
      - "{{ lobster_db_name }}-db:db"
      - "directory:directory"
    state: restarted
  tags:
    - lobsters_popularity

- name: add the container to microwizards tracking set
  command: "python {{ microwizard_sources }}/microwizard/mw.py add lobsters-pop {{ lobsters_popularity_container_name.stdout }}"