---
# file: roles/datawire-directory/tasks/main.yml

- name: ensure datawire directory data directory is created
  file:
    path: "{{ microwizard_docker_volumes }}/datawire"
    state: directory
  tags:
    - datawire-directory
    - infrastructure

- name: start datawire directory container
  docker:
    command: "/bin/bash -c '/usr/bin/directory -n $(hostname -i) -p 5672'"
    env:
      container_name: directory
      exposed_port: 5672
    expose:
      - 5672
    image: microwizard/base
    name: directory
    pull: missing
    restart_policy: on-failure
    restart_policy_retry: 3
    state: restarted
    volumes:
      - "{{ microwizard_docker_volumes }}/datawire:/etc/datawire"
  register: directory_container
  tags:
    - datawire-directory
    - infrastructure