#!/bin/bash -eu

# Provisions or reloads the lobsters application container.

if [ ! -d ".vagrant/" ]; then
  echo "error: .vagrant directory does not exist. run 'vagrant up' to provision the VM and create this directory"
  exit 1
fi

echo "---> provisioning lobsters monolith"
ansible-playbook\
  -i .vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory\
  -u vagrant\
  provisioning/microwizard_lobsters.yml
