#!/bin/bash -eu

if [ ! -d ".vagrant/" ]; then
  echo "error: .vagrant directory does not exist. run 'vagrant up' to provision the VM and create this directory"
  exit 1
fi

echo "---> restarting lobsters monolith"
vagrant ssh -c "docker restart lobsters" > /dev/null 2>&1

echo "---> waiting for lobsters monolith to become available"
until $(curl --output /dev/null --silent --head --fail http://127.0.0.1:3000); do
    printf '.'
    sleep 5
done

echo ""

