#!/bin/bash -eu

# ----------------------------------------------------------------------------------------------------------------------
# svkill
#
# Kills a running service on the MicroWizard host.
#
# Usage:
#   svkill <tag>
#

tag=$1

if [ ${#tag} -lt 3 ]; then
  echo "error: tag is too short (expected: 3 or more chars)"
  exit 1
fi

if [ ! -d ".vagrant/" ]; then
  echo "error: .vagrant directory does not exist. run 'vagrant up' to provision the VM and create this directory"
  exit 1
fi

ansible-playbook\
  -i .vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory\
  -u vagrant\
  --extra-vars "tag=${tag}"\
  provisioning/remove_service.yml