#!/bin/bash -e

# ----------------------------------------------------------------------------------------------------------------------
# svrun2
#
# Runs a new service on the MicroWizard host. The Git commit is optional and if not provided then the UNCOMMITTED
# changes will be used. This is handy for development since the development system filesystem is shared with vbox which
# then uses the source tree as a volume.
#
# Usage:
#   svrun2 <service_name> <tag> [git_commit]
#

service_name=$1
service_path="$(pwd)/src/${service_name}"
tag=$2
git_commit=${3:-UNCOMMITTED}

if [ ${#git_commit} -lt 8 ]; then
  echo "error: git commit hash is too short (expected: 8 or more chars)"
  exit 1
fi

if [ ${#tag} -lt 3 ]; then
  echo "error: tag is too short (expected: 3 or more chars)"
  exit 1
fi

if [ ! -d "src/${service_name}" ]; then
  echo "error: src/${service_name} directory does not exist."
  exit 1
fi

if [ ! -d ".vagrant/" ]; then
  echo "error: .vagrant directory does not exist. run 'vagrant up' to provision the VM and create this directory"
  exit 1
fi

echo "---> provisioning service... (name: ${service_name})"
ansible-playbook\
  -i .vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory\
  -u vagrant\
  --extra-vars\
    "service_path=${service_path}\
     service_name=${service_name}\
     tag=${tag}\
     git_commit=${git_commit}\
    "\
  provisioning/add_service.yml
