#!/bin/bash -e

# ----------------------------------------------------------------------------------------------------------------------
# svlaunch
#
# Runs a new service on the MicroWizard host.
#
# Usage:
#   svlaunch <tag> <git_commit>
#

tag=$1
git_commit=$2

if [ ${#git_commit} -lt 8 ]; then
  echo "error: git commit hash is too short (expected: 8 or more chars)"
  exit 1
fi

if [ ${#tag} -lt 3 ]; then
  echo "error: tag is too short (expected: 3 or more chars)"
  exit 1
fi

if [ ! -d ".vagrant/" ]; then
  echo "error: .vagrant directory does not exist. run 'vagrant up' to provision the VM and create this directory"
  exit 1
fi

ansible-playbook\
  -i .vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory\
  --extra-vars "tag=${tag} git_commit=${git_commit}"\
  ansible/add_service.yml
