---
- hosts: all
  remote_user: vagrant
  sudo: yes

  roles:
    - role: common
      datawire_repository: staging
    - role: mariadb
      db_name: lobster
      db_user: lobster
      db_password: lobster