---
- hosts: all
  remote_user: vagrant
  sudo: yes

  roles:
    - role: common
      datawire_repository: staging
    - role: datawire-directory
    - role: lobsters
#    - role: lobster-popularity-service