---
- hosts: all
  sudo: yes
  pre_tasks:
    - include_vars: "../src/lobsters/microwizard/microwizard.yml"
  roles:
    - role: common
      datawire_repository: staging
    - role: datawire-directory
    - role: lobsters