---
# file: roles/common/defaults/main.yml

# ------------------------------------------------------------------------------
# Datawire Configuration
# ------------------------------------------------------------------------------
datawire_repository: stable
datawire_repository_url: https://packagecloud.io/install/repositories/datawire/{{ datawire_repository }}/script.deb.sh

# ------------------------------------------------------------------------------
# System Configuration
# ------------------------------------------------------------------------------
essential_system_packages:
  - curl
  - gcc
  - git
  - python-pip
  - python-devel

essential_python_packages:
  - docker-py
  - docopt

# ------------------------------------------------------------------------------
# Docker Configuration
# ------------------------------------------------------------------------------

docker_users:
  - vagrant